#ifndef DEF_ICECROWN_CITADEL_H
#define DEF_ICECROWN_CITADEL_H

enum Data
{
    DATA_MARROWGAR_EVENT,
    DATA_DEATHWHISPER_EVENT,
        DATA_GUNSHIP_BATTLE_EVENT,
    DATA_SAURFANG_EVENT,
        DATA_FESTERGURT_EVENT,
        DATA_ROTFACE_EVENT,
        DATA_PROFESSOR_PUTRICIDE_EVENT,
        DATA_BLOOD_PRINCE_COUNCIL_EVENT,
        DATA_BLOOD_QUEEN_LANATHEL_EVENT,
        DATA_VALITHRIA_DREAMWALKER_EVENT,
        DATA_SINDRAGOSA_EVENT,
        DATA_LICH_KING_EVENT,
};

enum Data64
{
    DATA_MARROWGAR,
    DATA_DEATHWHISPER,
    DATA_SAURFANG,
        DATA_GUNSHIP_BATTLE,
        DATA_FESTERGURT,
        DATA_ROTFACE,
        DATA_PROFESSOR_PUTRICIDE,
        DATA_PRINCE_VALANAR_ICC,
        DATA_PRINCE_KELESETH_ICC,
        DATA_PRINCE_TALDARAM_ICC,
        DATA_BLOOD_QUEEN_LANATHEL,
        DATA_VALITHRIA_DREAMWALKER,
        DATA_SINDRAGOSA,
        DATA_LICH_KING,
};

enum mainCreatures
{
    CREATURE_MARROWGAR               = 36612,
    CREATURE_DEATHWHISPER            = 36855,
    CREATURE_SAURFANG                = 37813,
        CREATURE_FESTERGURT                              = 36626,
        CREATURE_ROTFACE                                 = 36627,
        CREATURE_PROFESSOR_PUTRICIDE     = 36678,
        CREATURE_PRINCE_VALANAR_ICC              = 37970,
        CREATURE_PRINCE_KELESETH_ICC     = 37972,
        CREATURE_PRINCE_TALDARAM_ICC     = 37973,
        CREATURE_BLOOD_QUEEN_LANATHEL    = 37955,
        CREATURE_VALITHRIA_DREAMWALKER   = 36789,
        CREATURE_SINDRAGOSA                              = 36853,
        CREATURE_LICH_KING                               = 36597,
};

#endif